# Generated by Django 6.0.1 on 2026-02-03 05:23

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Attendance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("check_in", models.DateTimeField(default=django.utils.timezone.now)),
                ("check_out", models.DateTimeField(blank=True, null=True)),
                ("date", models.DateField(default=django.utils.timezone.now)),
                ("on_break", models.BooleanField(default=False)),
                ("break_start", models.DateTimeField(blank=True, null=True)),
                (
                    "total_break_time",
                    models.DurationField(default=datetime.timedelta(0)),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
