# Generated by Django 6.0.1 on 2026-02-03 08:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("attendance", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="attendance",
            name="work_mode",
            field=models.CharField(
                choices=[
                    ("OFFICE", "In-Office"),
                    ("REMOTE", "Remote/WFH"),
                    ("FIELD", "Field Work"),
                ],
                default="OFFICE",
                max_length=10,
            ),
        ),
    ]
