# Generated by Django 6.0.1 on 2026-02-10 04:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("attendance", "0004_meeting"),
    ]

    operations = [
        migrations.AddField(
            model_name="attendance",
            name="is_at_office",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="attendance",
            name="latitude",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
        migrations.AddField(
            model_name="attendance",
            name="longitude",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
    ]
