# Generated by Django 6.0.1 on 2026-02-10 06:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("attendance", "0005_attendance_is_at_office_attendance_latitude_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="attendance",
            options={"verbose_name_plural": "Attendance Logs"},
        ),
    ]
