# Generated by Django 6.0.1 on 2026-02-10 07:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("attendance", "0006_alter_attendance_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendance",
            name="latitude",
            field=models.DecimalField(
                blank=True, decimal_places=9, max_digits=12, null=True
            ),
        ),
        migrations.AlterField(
            model_name="attendance",
            name="longitude",
            field=models.DecimalField(
                blank=True, decimal_places=9, max_digits=12, null=True
            ),
        ),
        migrations.AlterField(
            model_name="attendance",
            name="work_mode",
            field=models.CharField(default="OFFICE", max_length=20),
        ),
    ]
