# Generated by Django 6.0.1 on 2026-02-10 09:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("attendance", "0008_attendancelog"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendance",
            name="latitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="attendance",
            name="longitude",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
