# Generated by Django 6.0.1 on 2026-02-10 09:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("attendance", "0009_alter_attendance_latitude_alter_attendance_longitude"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendance",
            name="latitude",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
        migrations.AlterField(
            model_name="attendance",
            name="longitude",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
    ]
