# Generated by Django 6.0.1 on 2026-02-10 10:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("attendance", "0010_alter_attendance_latitude_alter_attendance_longitude"),
    ]

    operations = [
        migrations.AddField(
            model_name="attendance",
            name="break_type",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
