# Generated by Django 6.0.1 on 2026-02-10 11:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("attendance", "0011_attendance_break_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendance",
            name="break_type",
            field=models.CharField(
                blank=True,
                choices=[("SHORT", "Short Break"), ("LUNCH", "Lunch Break")],
                max_length=20,
                null=True,
            ),
        ),
    ]
