# Generated by Django 6.0.1 on 2026-02-10 12:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("attendance", "0013_announcement"),
    ]

    operations = [
        migrations.AlterField(
            model_name="announcement",
            name="title",
            field=models.CharField(max_length=255),
        ),
    ]
