# Generated by Django 6.0.1 on 2026-02-18 06:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("attendance", "0014_alter_announcement_title"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="meeting",
            options={"ordering": ["start_time"]},
        ),
        migrations.AlterModelOptions(
            name="task",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterField(
            model_name="announcement",
            name="title",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterUniqueTogether(
            name="attendance",
            unique_together={("user", "date")},
        ),
        migrations.DeleteModel(
            name="AttendanceLog",
        ),
    ]
